import { BillingAddon } from "./types";

export const BILLING_ADDONS: BillingAddon[] = [
  // 1. Transaction Add-ons (Usage / Billing-cycle allowance)
  {
    id: "addon-tx-100",
    code: "TX_100",
    name: "+100 Giao Dịch",
    type: "USAGE_PACK",
    metric: "TRANSACTIONS",
    increment_value: 100,
    display_value: "+100 Giao dịch",
    price: 39000,
    billing_cycle: "ONE_TIME",
    min_plan_required: "STARTER",
    is_active: true,
    description: "Bổ sung 100 lượt giao dịch xử lý đơn hàng trong chu kỳ hiện tại.",
  },
  {
    id: "addon-tx-500",
    code: "TX_500",
    name: "+500 Giao Dịch",
    type: "USAGE_PACK",
    metric: "TRANSACTIONS",
    increment_value: 500,
    display_value: "+500 Giao dịch",
    price: 99000,
    billing_cycle: "ONE_TIME",
    min_plan_required: "STARTER",
    is_active: true,
    description: "Bổ sung 500 lượt giao dịch xử lý đơn hàng trong chu kỳ hiện tại.",
  },
  {
    id: "addon-tx-1000",
    code: "TX_1000",
    name: "+1.000 Giao Dịch",
    type: "USAGE_PACK",
    metric: "TRANSACTIONS",
    increment_value: 1000,
    display_value: "+1.000 Giao dịch",
    price: 169000,
    billing_cycle: "ONE_TIME",
    min_plan_required: "STARTER",
    is_active: true,
    description: "Bổ sung 1.000 lượt giao dịch xử lý đơn hàng trong chu kỳ hiện tại.",
  },
  {
    id: "addon-tx-5000",
    code: "TX_5000",
    name: "+5.000 Giao Dịch",
    type: "USAGE_PACK",
    metric: "TRANSACTIONS",
    increment_value: 5000,
    display_value: "+5.000 Giao dịch",
    price: 499000,
    billing_cycle: "ONE_TIME",
    min_plan_required: "STARTER",
    is_active: true,
    description: "Bổ sung 5.000 lượt giao dịch xử lý đơn hàng trong chu kỳ hiện tại.",
  },

  // 2. Product Add-ons (Recurring monthly capacity)
  {
    id: "addon-prod-100",
    code: "PROD_100",
    name: "+100 Sản Phẩm Đang Hoạt Động",
    type: "CAPACITY_ADDON",
    metric: "ACTIVE_PRODUCTS",
    increment_value: 100,
    display_value: "+100 Sản phẩm",
    price: 19000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Tăng thêm 100 sản phẩm niêm yết công khai trên Storefront.",
  },
  {
    id: "addon-prod-500",
    code: "PROD_500",
    name: "+500 Sản Phẩm Đang Hoạt Động",
    type: "CAPACITY_ADDON",
    metric: "ACTIVE_PRODUCTS",
    increment_value: 500,
    display_value: "+500 Sản phẩm",
    price: 49000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Tăng thêm 500 sản phẩm niêm yết công khai trên Storefront.",
  },
  {
    id: "addon-prod-1000",
    code: "PROD_1000",
    name: "+1.000 Sản Phẩm Đang Hoạt Động",
    type: "CAPACITY_ADDON",
    metric: "ACTIVE_PRODUCTS",
    increment_value: 1000,
    display_value: "+1.000 Sản phẩm",
    price: 79000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Tăng thêm 1.000 sản phẩm niêm yết công khai trên Storefront.",
  },
  {
    id: "addon-prod-5000",
    code: "PROD_5000",
    name: "+5.000 Sản Phẩm Đang Hoạt Động",
    type: "CAPACITY_ADDON",
    metric: "ACTIVE_PRODUCTS",
    increment_value: 5000,
    display_value: "+5.000 Sản phẩm",
    price: 199000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Tăng thêm 5.000 sản phẩm niêm yết công khai trên Storefront.",
  },

  // 3. Storage Add-ons (Recurring monthly capacity)
  {
    id: "addon-storage-5gb",
    code: "STORAGE_5GB",
    name: "+5 GB Dung Lượng",
    type: "CAPACITY_ADDON",
    metric: "STORAGE_GB",
    increment_value: 5,
    display_value: "+5 GB",
    price: 19000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Bổ sung 5 GB lưu trữ hình ảnh sản phẩm và tài liệu hợp đồng.",
  },
  {
    id: "addon-storage-10gb",
    code: "STORAGE_10GB",
    name: "+10 GB Dung Lượng",
    type: "CAPACITY_ADDON",
    metric: "STORAGE_GB",
    increment_value: 10,
    display_value: "+10 GB",
    price: 29000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Bổ sung 10 GB lưu trữ hình ảnh sản phẩm và tài liệu hợp đồng.",
  },
  {
    id: "addon-storage-50gb",
    code: "STORAGE_50GB",
    name: "+50 GB Dung Lượng",
    type: "CAPACITY_ADDON",
    metric: "STORAGE_GB",
    increment_value: 50,
    display_value: "+50 GB",
    price: 99000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Bổ sung 50 GB lưu trữ hình ảnh sản phẩm và tài liệu hợp đồng.",
  },
  {
    id: "addon-storage-100gb",
    code: "STORAGE_100GB",
    name: "+100 GB Dung Lượng",
    type: "CAPACITY_ADDON",
    metric: "STORAGE_GB",
    increment_value: 100,
    display_value: "+100 GB",
    price: 169000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Bổ sung 100 GB lưu trữ dữ liệu quy mô lớn.",
  },
  {
    id: "addon-storage-500gb",
    code: "STORAGE_500GB",
    name: "+500 GB Dung Lượng",
    type: "CAPACITY_ADDON",
    metric: "STORAGE_GB",
    increment_value: 500,
    display_value: "+500 GB",
    price: 599000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Bổ sung 500 GB dung lượng siêu lớn cho doanh nghiệp.",
  },

  // 4. User Add-ons (Recurring monthly capacity)
  {
    id: "addon-user-1",
    code: "USER_1",
    name: "+1 Thành Viên Vận Hành",
    type: "CAPACITY_ADDON",
    metric: "USERS",
    increment_value: 1,
    display_value: "+1 Người dùng",
    price: 39000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Thêm 1 tài khoản nhân viên vận hành vào Workspace.",
  },
  {
    id: "addon-user-5",
    code: "USER_5",
    name: "+5 Thành Viên Vận Hành",
    type: "CAPACITY_ADDON",
    metric: "USERS",
    increment_value: 5,
    display_value: "+5 Người dùng",
    price: 149000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Thêm 5 tài khoản nhân viên vận hành vào Workspace.",
  },
  {
    id: "addon-user-10",
    code: "USER_10",
    name: "+10 Thành Viên Vận Hành",
    type: "CAPACITY_ADDON",
    metric: "USERS",
    increment_value: 10,
    display_value: "+10 Người dùng",
    price: 249000,
    billing_cycle: "RECURRING_MONTHLY",
    is_active: true,
    description: "Thêm 10 tài khoản nhân viên vận hành vào Workspace.",
  },

  // 5. Store Add-ons (Recurring monthly capacity)
  {
    id: "addon-store-1",
    code: "STORE_1",
    name: "+1 Cửa Hàng Trực Tuyến",
    type: "CAPACITY_ADDON",
    metric: "STORES",
    increment_value: 1,
    display_value: "+1 Store",
    price: 79000,
    billing_cycle: "RECURRING_MONTHLY",
    min_plan_required: "STARTER",
    is_active: true,
    description: "Mở thêm 1 gian hàng Storefront độc lập với tên miền riêng.",
  },
  {
    id: "addon-store-3",
    code: "STORE_3",
    name: "+3 Cửa Hàng Trực Tuyến",
    type: "CAPACITY_ADDON",
    metric: "STORES",
    increment_value: 3,
    display_value: "+3 Stores",
    price: 199000,
    billing_cycle: "RECURRING_MONTHLY",
    min_plan_required: "STARTER",
    is_active: true,
    description: "Mở thêm 3 gian hàng Storefront độc lập.",
  },
  {
    id: "addon-store-10",
    code: "STORE_10",
    name: "+10 Cửa Hàng Trực Tuyến",
    type: "CAPACITY_ADDON",
    metric: "STORES",
    increment_value: 10,
    display_value: "+10 Stores",
    price: 499000,
    billing_cycle: "RECURRING_MONTHLY",
    min_plan_required: "STARTER",
    is_active: true,
    description: "Mở thêm 10 gian hàng Storefront cho chuỗi chi nhánh.",
  },

  // 6. AI Token Packs
  {
    id: "addon-ai-mini",
    code: "AI_MINI",
    name: "AI Copilot Mini",
    type: "USAGE_PACK",
    metric: "AI_TOKENS",
    increment_value: 100000,
    display_value: "100.000 AI Tokens",
    price: 49000,
    billing_cycle: "ONE_TIME",
    is_active: true,
    description: "Gói AI viết mô tả sản phẩm và tự động trả lời báo giá.",
  },
  {
    id: "addon-ai-standard",
    code: "AI_STANDARD",
    name: "AI Copilot Standard",
    type: "USAGE_PACK",
    metric: "AI_TOKENS",
    increment_value: 250000,
    display_value: "250.000 AI Tokens",
    price: 99000,
    billing_cycle: "ONE_TIME",
    is_active: true,
    description: "Gói AI hỗ trợ đối soát đơn hàng và phân tích xu hướng bán hàng.",
  },
  {
    id: "addon-ai-pro",
    code: "AI_PRO",
    name: "AI Copilot Pro",
    type: "USAGE_PACK",
    metric: "AI_TOKENS",
    increment_value: 600000,
    display_value: "600.000 AI Tokens",
    price: 199000,
    billing_cycle: "ONE_TIME",
    is_active: true,
    description: "Gói AI chuyên sâu cho doanh nghiệp tăng trưởng nhanh.",
  },
  {
    id: "addon-ai-business",
    code: "AI_BUSINESS",
    name: "AI Copilot Business",
    type: "USAGE_PACK",
    metric: "AI_TOKENS",
    increment_value: 2000000,
    display_value: "2.000.000 AI Tokens",
    price: 499000,
    billing_cycle: "ONE_TIME",
    is_active: true,
    description: "Gói AI không giới hạn cho tự động hóa chuỗi cung ứng.",
  },
];
