import { BillingPlan, BillingPlanCode } from "./types";

export const BILLING_CONFIG = {
  CURRENT_MODE: "TEST_PAYMENT" as const, // 'DISABLED' | 'DISPLAY_ONLY' | 'TEST_PAYMENT' | 'LIVE_PAYMENT'
  IS_PUBLIC_TEST: true,
  PRICING_LABEL: "Gói Dịch Vụ & Bảng Giá",
  PUBLIC_TEST_NOTICE: "Public Test: Bạn có thể trải nghiệm toàn bộ quy trình thanh toán mô phỏng VietQR & kích hoạt tức thì.",
  DEFAULT_PAYMENT_BANK: {
    BANK_NAME: "MBBank (Ngân Hàng Quân Đội)",
    BANK_BIN: "970422",
    ACCOUNT_NUMBER: "0988123456888",
    ACCOUNT_NAME: "CONG TY CONG NGHE COMMERCE PLATFORM",
  },
  GRACE_PERIOD_DAYS: 7,
};

export const BILLING_PLANS: Record<BillingPlanCode, BillingPlan> = {
  FREE: {
    id: "plan-free",
    code: "FREE",
    name: "FREE",
    tagline: "Cho cá nhân và cửa hàng nhỏ mới bắt đầu",
    description: "Khởi đầu kinh doanh tức thì, không rủi ro, không phí ẩn.",
    display_order: 1,
    is_public: true,
    is_featured: false,
    prices: {
      MONTHLY: {
        billing_period: "MONTHLY",
        currency: "VND",
        amount: 0,
        monthly_equivalent: 0,
      },
      ANNUAL: {
        billing_period: "ANNUAL",
        currency: "VND",
        amount: 0,
        monthly_equivalent: 0,
      },
    },
    limits: {
      transactions_monthly: 50,
      active_products: 50,
      storage_bytes: 524288000, // 500 MB
      storage_display: "500 MB",
      users: 1,
      stores: 1,
    },
    features: {
      offers_unlimited: true,
      requests_unlimited: true,
      quotations_unlimited: true,
      order_checkout_vietqr: true,
      shipping_calculator: true,
      inventory_management: "BASIC",
      reporting: "BASIC",
      roles_permissions: "NONE",
      multi_store: false,
      multi_workspace: false,
      api_access: "NONE",
      transaction_verification: false,
      sla_support: "COMMUNITY",
      business_workflows: false,
    },
    feature_bullets: [
      "50 giao dịch / tháng",
      "50 sản phẩm đang hoạt động",
      "500 MB lưu trữ dữ liệu & hình ảnh",
      "1 người dùng quản trị",
      "1 cửa hàng trực tuyến (Storefront)",
      "Tạo Offer, Request & Báo giá không giới hạn",
      "Thanh toán mã QR VietQR tự động",
      "Quản lý tồn kho & Báo cáo cơ bản",
    ],
    cta_label: "BẮT ĐẦU MIỄN PHÍ",
  },

  STARTER: {
    id: "plan-starter",
    code: "STARTER",
    name: "STARTER",
    tagline: "Cho cửa hàng nhỏ đang phát triển",
    description: "Mở rộng khả năng xử lý đơn hàng và số lượng sản phẩm bán lẻ.",
    display_order: 2,
    is_public: true,
    is_featured: false,
    prices: {
      MONTHLY: {
        billing_period: "MONTHLY",
        currency: "VND",
        amount: 99000,
        monthly_equivalent: 99000,
      },
      ANNUAL: {
        billing_period: "ANNUAL",
        currency: "VND",
        amount: 990000,
        original_amount: 1188000,
        savings_amount: 198000,
        monthly_equivalent: 82500,
      },
    },
    limits: {
      transactions_monthly: 300,
      active_products: 300,
      storage_bytes: 3221225472, // 3 GB
      storage_display: "3 GB",
      users: 2,
      stores: 1,
    },
    features: {
      offers_unlimited: true,
      requests_unlimited: true,
      quotations_unlimited: true,
      order_checkout_vietqr: true,
      shipping_calculator: true,
      inventory_management: "BASIC",
      reporting: "BASIC",
      roles_permissions: "BASIC",
      multi_store: false,
      multi_workspace: false,
      api_access: "NONE",
      transaction_verification: false,
      sla_support: "STANDARD",
      business_workflows: false,
    },
    feature_bullets: [
      "300 giao dịch / tháng",
      "300 sản phẩm đang hoạt động",
      "3 GB lưu trữ tốc độ cao",
      "2 tài khoản nhân viên",
      "1 cửa hàng Storefront",
      "Tất cả quyền lợi của gói FREE",
      "Phân quyền nhân viên cơ bản",
      "Hỗ trợ kỹ thuật Standard",
    ],
    cta_label: "CHỌN STARTER",
  },

  PRO: {
    id: "plan-pro",
    code: "PRO",
    name: "PRO",
    tagline: "Cho doanh nghiệp đang tăng trưởng mạnh mẽ",
    description: "Giải pháp toàn diện tối ưu chuỗi cung ứng, tồn kho và đa điểm bán.",
    display_order: 3,
    is_public: true,
    is_featured: true,
    highlight_badge: "PHỔ BIẾN NHẤT",
    prices: {
      MONTHLY: {
        billing_period: "MONTHLY",
        currency: "VND",
        amount: 249000,
        monthly_equivalent: 249000,
      },
      ANNUAL: {
        billing_period: "ANNUAL",
        currency: "VND",
        amount: 2490000,
        original_amount: 2988000,
        savings_amount: 498000,
        monthly_equivalent: 207500,
      },
    },
    limits: {
      transactions_monthly: 1500,
      active_products: 2000,
      storage_bytes: 16106127360, // 15 GB
      storage_display: "15 GB",
      users: 5,
      stores: 3,
    },
    features: {
      offers_unlimited: true,
      requests_unlimited: true,
      quotations_unlimited: true,
      order_checkout_vietqr: true,
      shipping_calculator: true,
      inventory_management: "ADVANCED",
      reporting: "ADVANCED",
      roles_permissions: "ADVANCED",
      multi_store: true,
      multi_workspace: true,
      api_access: "LIMITED",
      transaction_verification: true,
      sla_support: "PRIORITY",
      business_workflows: true,
    },
    feature_bullets: [
      "1.500 giao dịch / tháng",
      "2.000 sản phẩm đang hoạt động",
      "15 GB lưu trữ media dung lượng lớn",
      "5 tài khoản nhân viên phân quyền",
      "3 cửa hàng trực tuyến độc lập",
      "Quản lý tồn kho nâng cao & cảnh báo thông minh",
      "Báo cáo tài chính & doanh thu chuyên sâu",
      "Xác thực giao dịch (Transaction Verification)",
      "Hỗ trợ ưu tiên (Priority Support)",
    ],
    cta_label: "CHỌN PRO",
  },

  BUSINESS: {
    id: "plan-business",
    code: "BUSINESS",
    name: "BUSINESS",
    tagline: "Cho doanh nghiệp quy mô lớn và đa chi nhánh",
    description: "Sức chứa tối đa, đa cửa hàng và hỗ trợ API kết nối ERP / CRM.",
    display_order: 4,
    is_public: true,
    is_featured: false,
    prices: {
      MONTHLY: {
        billing_period: "MONTHLY",
        currency: "VND",
        amount: 499000,
        monthly_equivalent: 499000,
      },
      ANNUAL: {
        billing_period: "ANNUAL",
        currency: "VND",
        amount: 4990000,
        original_amount: 5988000,
        savings_amount: 998000,
        monthly_equivalent: 415833,
      },
    },
    limits: {
      transactions_monthly: 5000,
      active_products: 10000,
      storage_bytes: 53687091200, // 50 GB
      storage_display: "50 GB",
      users: 15,
      stores: 10,
    },
    features: {
      offers_unlimited: true,
      requests_unlimited: true,
      quotations_unlimited: true,
      order_checkout_vietqr: true,
      shipping_calculator: true,
      inventory_management: "ADVANCED",
      reporting: "ADVANCED",
      roles_permissions: "ADVANCED",
      multi_store: true,
      multi_workspace: true,
      api_access: "FULL",
      transaction_verification: true,
      sla_support: "DEDICATED_24_7",
      business_workflows: true,
    },
    feature_bullets: [
      "5.000 giao dịch / tháng",
      "10.000 sản phẩm đang hoạt động",
      "50 GB lưu trữ dữ liệu an toàn",
      "15 tài khoản nhân viên",
      "10 cửa hàng Storefront",
      "Toàn bộ tính năng nâng cao & Workflow doanh nghiệp",
      "Kết nối API tích hợp hệ sinh thái",
      "Xác thực sổ cái tin cậy & Audit Trail",
      "Hỗ trợ kỹ thuật 24/7",
    ],
    cta_label: "CHỌN BUSINESS",
  },

  ENTERPRISE: {
    id: "plan-enterprise",
    code: "ENTERPRISE",
    name: "ENTERPRISE",
    tagline: "Cho tập đoàn và nhu cầu tùy biến hạ tầng riêng",
    description: "Hạ tầng riêng biệt, SLA cam kết 99.99% và tích hợp theo yêu cầu.",
    display_order: 5,
    is_public: true,
    is_featured: false,
    prices: {
      MONTHLY: {
        billing_period: "MONTHLY",
        currency: "VND",
        amount: 0, // Contact
      },
      ANNUAL: {
        billing_period: "ANNUAL",
        currency: "VND",
        amount: 0, // Contact
      },
    },
    limits: {
      transactions_monthly: null,
      active_products: null,
      storage_bytes: null,
      storage_display: "Không giới hạn",
      users: null,
      stores: null,
    },
    features: {
      offers_unlimited: true,
      requests_unlimited: true,
      quotations_unlimited: true,
      order_checkout_vietqr: true,
      shipping_calculator: true,
      inventory_management: "ADVANCED",
      reporting: "ADVANCED",
      roles_permissions: "ADVANCED",
      multi_store: true,
      multi_workspace: true,
      api_access: "CUSTOM",
      transaction_verification: true,
      sla_support: "DEDICATED_24_7",
      business_workflows: true,
    },
    feature_bullets: [
      "Không giới hạn số lượng giao dịch",
      "Không giới hạn sản phẩm & người dùng",
      "Dung lượng lưu trữ theo yêu cầu riêng",
      "Cam kết SLA 99.99% dịch vụ",
      "Tích hợp hệ thống ERP/CRM nội bộ",
      "Hỗ trợ kỹ sư chuyên trách 24/7",
      "Triển khai hạ tầng Private Cloud hoặc On-Premise",
    ],
    cta_label: "LIÊN HỆ TƯ VẤN",
  },
};

export const PLANS_ARRAY = Object.values(BILLING_PLANS).sort(
  (a, b) => a.display_order - b.display_order
);
