import { DOMAIN_CONFIG } from "./domain";

export const PWA_CONFIG = {
  APP_NAME: DOMAIN_CONFIG.BRAND_NAME,
  APP_SHORT_NAME: DOMAIN_CONFIG.BRAND_SHORT_NAME,
  APP_DESCRIPTION: DOMAIN_CONFIG.BRAND_TAGLINE,
  APP_THEME_COLOR: "#00A88F",
  APP_BACKGROUND_COLOR: "#0D1B2A",
  PUBLIC_APP_URL: DOMAIN_CONFIG.PUBLIC_APP_URL,
  PWA_START_URL: "/",
  VERSION: "2.1.0",

  // Install Eligibility Thresholds (Value First Principle)
  INSTALL_MIN_SESSIONS: 1,
  INSTALL_MIN_TRANSACTIONS: 0,
  INSTALL_COOLDOWN_DAYS: 7,

  // Storage Keys
  STORAGE_KEYS: {
    INSTALL_DISMISSED_AT: "pwa_install_dismissed_at",
    SESSION_COUNT: "pwa_session_count",
    INSTALLED_DETECTED: "pwa_installed_detected",
  },
};
