import { StoreTemplate } from "@/types";

/**
 * STORE TEMPLATE SYSTEM & TEMPLATE MARKETPLACE DEFINITIONS
 * 
 * 10 FREE Templates (0 VND)
 * 5 PREMIUM Templates (200.000 VND / one-time digital purchase)
 */

export const STORE_TEMPLATES: StoreTemplate[] = [
  // =========================================================================
  // 10 FREE TEMPLATES (0 VND)
  // =========================================================================
  {
    id: "tpl_free_minimal",
    code: "FREE_MINIMAL",
    name: "Minimal",
    description: "Tối giản, tinh tế, tối đa không gian trắng. Tập trung trực diện vào sản phẩm và ưu đãi.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "RETAIL",
    badge_text: "MIỄN PHÍ",
    preview_thumbnail_desktop: "/templates/minimal-desktop.png",
    preview_thumbnail_mobile: "/templates/minimal-mobile.png",
    features: [
      "Bố cục tinh gọn, không rườm rà",
      "Tối ưu tốc độ tải trang cực nhanh",
      "Phù hợp cá nhân bán hàng và cửa hàng nhỏ",
      "Lưới sản phẩm chuẩn tỉ lệ 1:1"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "lg",
      container_width: "standard",
      hero_layout: "minimal",
      product_card_style: "minimal",
      header_style: "standard",
      color_palette_default: {
        primary: "#2563eb",
        accent: "#3b82f6",
        background: "#ffffff",
        surface: "#f8fafc",
        text: "#0f172a",
      },
    },
    default_sections: ["hero", "categories", "featured_offers", "products", "trust_bar", "policies", "contact"],
  },
  {
    id: "tpl_free_modern",
    code: "FREE_MODERN",
    name: "Modern",
    description: "Phong cách SaaS hiện đại, hero banner ấn tượng, các thẻ bo tròn và lời gọi hành động nổi bật.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "RETAIL",
    badge_text: "PHỔ BIẾN",
    preview_thumbnail_desktop: "/templates/modern-desktop.png",
    preview_thumbnail_mobile: "/templates/modern-mobile.png",
    features: [
      "Hero banner lớn với nút Call-To-Action sắc nét",
      "Thẻ sản phẩm bo tròn mềm mại và hiệu ứng hover",
      "Tích hợp thanh uy tín bảo mật Trust Bar",
      "Phù hợp thương hiệu hiện đại và bán hàng online"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "2xl",
      container_width: "wide",
      hero_layout: "banner",
      product_card_style: "elevated",
      header_style: "standard",
      color_palette_default: {
        primary: "#4f46e5",
        accent: "#6366f1",
        background: "#ffffff",
        surface: "#f1f5f9",
        text: "#0f172a",
      },
    },
    default_sections: ["hero", "trust_bar", "featured_offers", "categories", "products", "about", "policies", "contact"],
  },
  {
    id: "tpl_free_catalog",
    code: "FREE_CATALOG",
    name: "Catalog",
    description: "Chuyên biệt cho danh mục lớn, lưới sản phẩm mật độ cao, tìm kiếm và lọc danh mục nổi bật.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "RETAIL",
    badge_text: "DANH MỤC LỚN",
    preview_thumbnail_desktop: "/templates/catalog-desktop.png",
    preview_thumbnail_mobile: "/templates/catalog-mobile.png",
    features: [
      "Bộ lọc danh mục dạng thanh trượt trực quan",
      "Lưới sản phẩm hiển thị nhiều thông số",
      "Thích hợp cửa hàng bán sỉ, linh kiện, phụ tùng",
      "Tìm kiếm nhanh và nút thêm giỏ hàng liền tay"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "md",
      container_width: "wide",
      hero_layout: "centered",
      product_card_style: "bordered",
      header_style: "stacked",
      color_palette_default: {
        primary: "#0284c7",
        accent: "#0ea5e9",
        background: "#ffffff",
        surface: "#f8fafc",
        text: "#0f172a",
      },
    },
    default_sections: ["categories", "products", "featured_offers", "trust_bar", "policies", "contact"],
  },
  {
    id: "tpl_free_service",
    code: "FREE_SERVICE",
    name: "Service",
    description: "Tối ưu cho nhà cung cấp dịch vụ, tư vấn, sửa chữa, freelancer với thẻ báo giá và form liên hệ.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "SERVICE",
    badge_text: "DỊCH VỤ",
    preview_thumbnail_desktop: "/templates/service-desktop.png",
    preview_thumbnail_mobile: "/templates/service-mobile.png",
    features: [
      "Thẻ gói dịch vụ và bảng giá chi tiết",
      "Khối giới thiệu kinh nghiệm và năng lực",
      "Nút yêu cầu báo giá và tư vấn trực tiếp",
      "Tối ưu cho chuyên gia và đơn vị kỹ thuật"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "xl",
      container_width: "standard",
      hero_layout: "split",
      product_card_style: "elevated",
      header_style: "standard",
      color_palette_default: {
        primary: "#059669",
        accent: "#10b981",
        background: "#ffffff",
        surface: "#f0fdf4",
        text: "#0f172a",
      },
    },
    default_sections: ["hero", "about", "services", "featured_offers", "trust_bar", "reviews", "contact"],
  },
  {
    id: "tpl_free_local",
    code: "FREE_LOCAL",
    name: "Local",
    description: "Thân thiện với cửa hàng địa phương, quán ăn, xưởng gia đình. Nổi bật địa chỉ và giờ mở cửa.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "LOCAL",
    badge_text: "ĐỊA PHƯƠNG",
    preview_thumbnail_desktop: "/templates/local-desktop.png",
    preview_thumbnail_mobile: "/templates/local-mobile.png",
    features: [
      "Khối thông tin địa chỉ, giờ mở cửa và số hotline ưu tiên",
      "Hỗ trợ nhận hàng tại cửa hàng (Store Pickup)",
      "Bố cục ấm cúng, gần gũi với khách hàng lân cận",
      "Dễ dàng xem bản đồ chỉ đường"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "2xl",
      container_width: "standard",
      hero_layout: "centered",
      product_card_style: "elevated",
      header_style: "centered",
      color_palette_default: {
        primary: "#d97706",
        accent: "#f59e0b",
        background: "#ffffff",
        surface: "#fffbeb",
        text: "#1c1917",
      },
    },
    default_sections: ["hero", "featured_offers", "products", "about", "trust_bar", "contact", "policies"],
  },
  {
    id: "tpl_free_business",
    code: "FREE_BUSINESS",
    name: "Business",
    description: "Chuẩn mực doanh nghiệp SME, nhà sản xuất và thương mại B2B với hồ sơ năng lực rõ ràng.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "CORPORATE",
    badge_text: "DOANH NGHIỆP",
    preview_thumbnail_desktop: "/templates/business-desktop.png",
    preview_thumbnail_mobile: "/templates/business-mobile.png",
    features: [
      "Cấu trúc trang nghiêm túc, chuyên nghiệp",
      "Hiển thị mã số thuế, chứng nhận và pháp nhân",
      "Khối sản phẩm & năng lực cung ứng số lượng lớn",
      "Nút gửi RFQ / Báo giá thương mại trực tiếp"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "lg",
      container_width: "wide",
      hero_layout: "split",
      product_card_style: "bordered",
      header_style: "standard",
      color_palette_default: {
        primary: "#0f766e",
        accent: "#14b8a6",
        background: "#ffffff",
        surface: "#f0fdfa",
        text: "#0f172a",
      },
    },
    default_sections: ["hero", "trust_bar", "products", "services", "featured_offers", "about", "policies", "contact"],
  },
  {
    id: "tpl_free_showcase",
    code: "FREE_SHOWCASE",
    name: "Showcase",
    description: "Tập trung thị giác, hình ảnh lớn, tối ưu cho thời trang, đồ thủ công, nội thất và decor.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "SHOWCASE",
    badge_text: "HÌNH ẢNH LỚN",
    preview_thumbnail_desktop: "/templates/showcase-desktop.png",
    preview_thumbnail_mobile: "/templates/showcase-mobile.png",
    features: [
      "Khung ảnh tỷ lệ 16:9 và 4:3 siêu nét",
      "Tối giản phần văn bản, tôn vinh hình ảnh sản phẩm",
      "Bộ sưu tập ảnh phong cách Lookbook",
      "Thích hợp nghệ thuật, may mặc, nội thất"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "2xl",
      container_width: "fluid",
      hero_layout: "banner",
      product_card_style: "editorial",
      header_style: "transparent",
      color_palette_default: {
        primary: "#18181b",
        accent: "#71717a",
        background: "#fafafa",
        surface: "#ffffff",
        text: "#09090b",
      },
    },
    default_sections: ["hero", "featured_offers", "categories", "products", "about", "trust_bar", "contact"],
  },
  {
    id: "tpl_free_compact",
    code: "FREE_COMPACT",
    name: "Compact",
    description: "Tối ưu siêu tốc cho Mobile & Zalo, danh sách dạng hàng ngang gọn gàng, đặt hàng nhanh.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "RETAIL",
    badge_text: "SIÊU NHẸ",
    preview_thumbnail_desktop: "/templates/compact-desktop.png",
    preview_thumbnail_mobile: "/templates/compact-mobile.png",
    features: [
      "Thời gian nạp trang dưới 0.5 giây trên 4G/5G",
      "Danh sách sản phẩm dạng thẻ gọn nhẹ (List View)",
      "Nút mua nhanh cố định trên điện thoại",
      "Cực kỳ phù hợp tiếp cận khách qua link Zalo/Facebook"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "xl",
      container_width: "compact",
      hero_layout: "minimal",
      product_card_style: "compact",
      header_style: "standard",
      color_palette_default: {
        primary: "#dc2626",
        accent: "#ef4444",
        background: "#ffffff",
        surface: "#fef2f2",
        text: "#18181b",
      },
    },
    default_sections: ["featured_offers", "products", "categories", "trust_bar", "contact"],
  },
  {
    id: "tpl_free_professional",
    code: "FREE_PROFESSIONAL",
    name: "Professional",
    description: "Phong cách chuẩn mực, đề cao chỉ số tin cậy (Trust Score), hồ sơ xác thực và chính sách minh bạch.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "CORPORATE",
    badge_text: "UY TÍN CAO",
    preview_thumbnail_desktop: "/templates/professional-desktop.png",
    preview_thumbnail_mobile: "/templates/professional-mobile.png",
    features: [
      "Thanh chứng thực chữ ký số & Merkle Trust nổi bật",
      "Định dạng thông tin rõ ràng, trang nhã",
      "Trưng bày đầy đủ chính sách đổi trả và bảo hành",
      "Phù hợp ngành đào tạo, y tế, dịch vụ chuyên môn"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "lg",
      container_width: "wide",
      hero_layout: "split",
      product_card_style: "bordered",
      header_style: "standard",
      color_palette_default: {
        primary: "#334155",
        accent: "#475569",
        background: "#ffffff",
        surface: "#f8fafc",
        text: "#0f172a",
      },
    },
    default_sections: ["hero", "trust_bar", "featured_offers", "products", "services", "about", "policies", "contact"],
  },
  {
    id: "tpl_free_market",
    code: "FREE_MARKET",
    name: "Market",
    description: "Đậm chất sàn thương mại, làm nổi bật khuyến mãi sốc, ưu đãi giờ vàng và nút Thêm Giỏ Hàng liền tay.",
    pricing_type: "FREE",
    price: 0,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "RETAIL",
    badge_text: "BÁN CHẠY",
    preview_thumbnail_desktop: "/templates/market-desktop.png",
    preview_thumbnail_mobile: "/templates/market-mobile.png",
    features: [
      "Băng chuyền khuyến mãi & Flash Sale nổi bật",
      "Thẻ giảm giá % và giá gốc so sánh trực quan",
      "Giỏ hàng nhanh và mua nhiều giảm giá",
      "Phù hợp bán lẻ tiêu dùng, thời trang, bách hóa"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "2xl",
      container_width: "wide",
      hero_layout: "banner",
      product_card_style: "elevated",
      header_style: "standard",
      color_palette_default: {
        primary: "#ea580c",
        accent: "#f97316",
        background: "#ffffff",
        surface: "#fff7ed",
        text: "#1c1917",
      },
    },
    default_sections: ["featured_offers", "hero", "categories", "products", "trust_bar", "reviews", "policies", "contact"],
  },

  // =========================================================================
  // 5 PREMIUM TEMPLATES (200.000 VND / MẪU - MUA 1 LẦN DÙNG VĨNH VIỄN)
  // =========================================================================
  {
    id: "tpl_premium_signature",
    code: "PREMIUM_SIGNATURE",
    name: "Signature",
    description: "Tối giản thượng hạng. Typography tinh tế, khoảng cách thở sang trọng, phong cách thương hiệu cao cấp.",
    pricing_type: "PAID",
    price: 200000,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "FLAGSHIP",
    badge_text: "CAO CẤP",
    preview_thumbnail_desktop: "/templates/signature-desktop.png",
    preview_thumbnail_mobile: "/templates/signature-mobile.png",
    features: [
      "Thiết kế Luxury tối giản với đường nét viền mảnh tinh xảo",
      "Typography phân cấp chuẩn quốc tế, sang trọng",
      "Khối Hero tương tác toàn màn hình với hiệu ứng tinh tế",
      "Định vị thương hiệu hàng đầu cho trang sức, đồng hồ, mỹ phẩm cao cấp"
    ],
    design_tokens: {
      font_family: "font-serif",
      border_radius: "none",
      container_width: "compact",
      hero_layout: "storytelling",
      product_card_style: "editorial",
      header_style: "centered",
      color_palette_default: {
        primary: "#09090b",
        accent: "#d4af37",
        background: "#ffffff",
        surface: "#fafafa",
        text: "#18181b",
      },
    },
    default_sections: ["hero", "featured_offers", "products", "about", "trust_bar", "reviews", "contact"],
  },
  {
    id: "tpl_premium_commerce_pro",
    code: "PREMIUM_COMMERCE_PRO",
    name: "Commerce Pro",
    description: "Mẫu E-Commerce nâng cao. Mega Menu hiện đại, bộ lọc đa tầng, sticky action bar và thúc đẩy chuyển đổi tối đa.",
    pricing_type: "PAID",
    price: 200000,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "FLAGSHIP",
    badge_text: "CAO CẤP",
    preview_thumbnail_desktop: "/templates/commerce-pro-desktop.png",
    preview_thumbnail_mobile: "/templates/commerce-pro-mobile.png",
    features: [
      "Thanh Sticky Action Bar dưới chân màn hình Mobile",
      "Hộp lọc thông minh nhiều thuộc tính (giá, loại, phân loại)",
      "Khối Banner ưu đãi kép và thông báo đơn hàng thời gian thực",
      "Tối ưu tỷ lệ chuyển đổi đơn hàng cho shop lớn"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "2xl",
      container_width: "fluid",
      hero_layout: "banner",
      product_card_style: "elevated",
      header_style: "standard",
      color_palette_default: {
        primary: "#7c3aed",
        accent: "#8b5cf6",
        background: "#ffffff",
        surface: "#f5f3ff",
        text: "#0f172a",
      },
    },
    default_sections: ["hero", "trust_bar", "featured_offers", "categories", "products", "reviews", "policies", "contact"],
  },
  {
    id: "tpl_premium_corporate_pro",
    code: "PREMIUM_CORPORATE_PRO",
    name: "Corporate Pro",
    description: "Chuẩn mực tập đoàn B2B, doanh nghiệp công nghiệp, tổng thầu. Trưng bày năng lực, chứng chỉ và quy mô.",
    pricing_type: "PAID",
    price: 200000,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "CORPORATE",
    badge_text: "CAO CẤP",
    preview_thumbnail_desktop: "/templates/corporate-pro-desktop.png",
    preview_thumbnail_mobile: "/templates/corporate-pro-mobile.png",
    features: [
      "Bố cục trang trọng thể hiện tầm vóc tập đoàn",
      "Khối trưng bày chứng chỉ ISO, giải thưởng và đối tác chiến lược",
      "Báo giá theo lô, số lượng lớn và hợp đồng nguyên tắc",
      "Tích hợp xác thực giao dịch minh bạch chuỗi cung ứng"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "md",
      container_width: "wide",
      hero_layout: "split",
      product_card_style: "bordered",
      header_style: "stacked",
      color_palette_default: {
        primary: "#1e3a8a",
        accent: "#2563eb",
        background: "#ffffff",
        surface: "#eff6ff",
        text: "#0f172a",
      },
    },
    default_sections: ["hero", "trust_bar", "about", "products", "services", "featured_offers", "policies", "contact"],
  },
  {
    id: "tpl_premium_studio_pro",
    code: "PREMIUM_STUDIO_PRO",
    name: "Studio Pro",
    description: "Kể chuyện thương hiệu bằng hình ảnh (Visual Storytelling). Bố cục dạng tạp chí cao cấp, đậm chất sáng tạo.",
    pricing_type: "PAID",
    price: 200000,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "SHOWCASE",
    badge_text: "CAO CẤP",
    preview_thumbnail_desktop: "/templates/studio-pro-desktop.png",
    preview_thumbnail_mobile: "/templates/studio-pro-mobile.png",
    features: [
      "Bố cục tạp chí nghệ thuật (Editorial Layouts)",
      "Banner toàn cảnh tràn màn hình với độ tương phản sâu",
      "Khối Lookbook trình diễn bộ sưu tập độc quyền",
      "Tối ưu cho kiến trúc, thiết kế, studio ảnh, thời trang may đo"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "2xl",
      container_width: "fluid",
      hero_layout: "storytelling",
      product_card_style: "editorial",
      header_style: "transparent",
      color_palette_default: {
        primary: "#18181b",
        accent: "#e11d48",
        background: "#09090b",
        surface: "#18181b",
        text: "#f4f4f5",
      },
    },
    default_sections: ["hero", "about", "featured_offers", "products", "trust_bar", "reviews", "contact"],
  },
  {
    id: "tpl_premium_prime",
    code: "PREMIUM_PRIME",
    name: "Prime",
    description: "Mẫu giao diện cờ đầu (Flagship). Trải nghiệm đỉnh cao, biến trang cửa hàng thành website chuyên nghiệp độc lập.",
    pricing_type: "PAID",
    price: 200000,
    currency: "VND",
    status: "ACTIVE",
    version: "1.0",
    category: "FLAGSHIP",
    badge_text: "FLAGSHIP",
    preview_thumbnail_desktop: "/templates/prime-desktop.png",
    preview_thumbnail_mobile: "/templates/prime-mobile.png",
    features: [
      "Giao diện chuẩn website thương mại điện tử độc lập hàng đầu",
      "Hệ thống định vị thương hiệu đẳng cấp toàn diện",
      "Bố cục linh hoạt theo danh mục hàng hóa hoặc dịch vụ",
      "Tối ưu hoàn hảo trên mọi thiết bị và trình duyệt Zalo Mobile"
    ],
    design_tokens: {
      font_family: "font-sans",
      border_radius: "2xl",
      container_width: "wide",
      hero_layout: "banner",
      product_card_style: "elevated",
      header_style: "standard",
      color_palette_default: {
        primary: "#0284c7",
        accent: "#38bdf8",
        background: "#ffffff",
        surface: "#f0f9ff",
        text: "#0f172a",
      },
    },
    default_sections: ["hero", "trust_bar", "featured_offers", "categories", "products", "about", "reviews", "policies", "contact"],
  },
];

/**
 * DEFAULT TEMPLATE ID
 */
export const DEFAULT_TEMPLATE_ID = "tpl_free_minimal";
export const DEFAULT_TEMPLATE_CODE = "FREE_MINIMAL";

/**
 * Runtime Demo Dataset for Interactive Live Preview
 * Isolated from real database!
 */
export const DEMO_STORE_DATASET = {
  store: {
    id: "demo_store_preview",
    store_name: "NOVA Flagship Store",
    slug: "demo-nova",
    owner_actor_id: "demo_actor_id",
    owner_actor_type: "ORGANIZATION" as const,
    logo_url: "https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=150&auto=format&fit=crop&q=80",
    cover_image_url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1600&auto=format&fit=crop&q=80",
    description: "Thương hiệu phân phối sản phẩm phong cách sống cao cấp, thiết bị thông minh và dịch vụ bảo hành chuẩn chính hãng.",
    phone: "0908 123 456",
    email: "contact@novastore.vn",
    address: "Số 88 Phố Huế, Quận Hai Bà Trưng, TP. Hà Nội",
    is_active: true,
    active_template_id: "tpl_free_minimal",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  organization: {
    id: "org_demo_preview",
    name: "NOVA Technology & Lifestyle Co., Ltd",
    slug: "nova-corp",
    org_type: "COMPANY" as const,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  categories: [
    { id: "cat_1", organization_id: "org_demo_preview", name: "Thiết Bị Thông Minh", slug: "thiet-bi-thong-minh", display_order: 1, created_at: new Date().toISOString() },
    { id: "cat_2", organization_id: "org_demo_preview", name: "Đồ Gia Dụng Cao Cấp", slug: "do-gia-dung", display_order: 2, created_at: new Date().toISOString() },
    { id: "cat_3", organization_id: "org_demo_preview", name: "Phụ Kiện & Decor", slug: "phu-kien-decor", display_order: 3, created_at: new Date().toISOString() },
    { id: "cat_4", organization_id: "org_demo_preview", name: "Dịch Vụ Lắp Đặt", slug: "dich-vu-lap-dat", display_order: 4, created_at: new Date().toISOString() },
  ],
  products: [
    {
      id: "demo_p1",
      organization_id: "org_demo_preview",
      name: "Loa Thông Minh Studio Hi-Fi SoundMaster",
      price: 3200000,
      compare_at_price: 3800000,
      unit: "chiếc",
      category: "cat_1",
      image_url: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
      description: "Âm thanh vòm 360 độ, kết nối Bluetooth 5.3 & AirPlay 2, trợ lý ảo giọng nói tiếng Việt.",
      product_status: "ACTIVE" as const,
      availability_status: "IN_STOCK" as const,
      is_available: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "demo_p2",
      organization_id: "org_demo_preview",
      name: "Đèn Bàn Cảm Ứng Tự Động Điều Chỉnh Quang Phổ",
      price: 850000,
      compare_at_price: 1100000,
      unit: "cái",
      category: "cat_3",
      image_url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80",
      description: "Chống cận thị chuẩn y khoa, sạc không dây 15W tích hợp chân đế, thân nhôm nguyên khối.",
      product_status: "ACTIVE" as const,
      availability_status: "IN_STOCK" as const,
      is_available: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "demo_p3",
      organization_id: "org_demo_preview",
      name: "Máy Pha Cà Phê Espresso Mini Cầm Tay",
      price: 1650000,
      compare_at_price: 1950000,
      unit: "bộ",
      category: "cat_2",
      image_url: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80",
      description: "Áp suất 18 bar chuẩn Ý, nhỏ gọn mang đi du lịch hoặc văn phòng, chiết xuất crema dày mịn.",
      product_status: "ACTIVE" as const,
      availability_status: "IN_STOCK" as const,
      is_available: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "demo_p4",
      organization_id: "org_demo_preview",
      name: "Đồng Hồ Thông Minh HealthTrack Pro Titanium",
      price: 4900000,
      compare_at_price: 5500000,
      unit: "chiếc",
      category: "cat_1",
      image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
      description: "Màn hình AMOLED sapphire, đo điện tâm đồ ECG và SPO2 24/7, thời lượng pin 14 ngày.",
      product_status: "ACTIVE" as const,
      availability_status: "IN_STOCK" as const,
      is_available: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "demo_p5",
      organization_id: "org_demo_preview",
      name: "Bộ Ghế Công Thái Học ErgoMaster Mesh V2",
      price: 3890000,
      compare_at_price: 4500000,
      unit: "bộ",
      category: "cat_3",
      image_url: "https://images.unsplash.com/photo-1580481077150-13f5d548301b?w=800&auto=format&fit=crop&q=80",
      description: "Lưới Wintex nhập khẩu Hàn Quốc, đệm đỡ thắt lưng tự thích ứng, bảo hành 3 năm.",
      product_status: "ACTIVE" as const,
      availability_status: "IN_STOCK" as const,
      is_available: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "demo_p6",
      organization_id: "org_demo_preview",
      name: "Gói Dịch Vụ Cài Đặt & Cấu Hình Smart Home Tận Nơi",
      price: 1200000,
      unit: "gói",
      category: "cat_4",
      image_url: "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
      description: "Kỹ sư chuyên nghiệp khảo sát, lắp đặt kịch bản tự động hóa nhà thông minh trong 24h.",
      product_status: "ACTIVE" as const,
      availability_status: "IN_STOCK" as const,
      is_available: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  offers: [
    {
      id: "demo_offer_1",
      organization_id: "org_demo_preview",
      store_id: "demo_store_preview",
      offer_type: "PRODUCT" as const,
      inventory_tracking: false,
      name: "Combo Nhà Đẹp Smart Living (Loa + Đèn + Máy Pha Cafe)",
      slug: "combo-smart-living",
      price: 5200000,
      compare_at_price: 6550000,
      short_description: "Ưu đãi trọn gói mùa tựu trường và tân gia, tiết kiệm tới 1.350.000đ khi đặt mua online.",
      image_url: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=80",
      status: "ACTIVE" as const,
      visibility: "PUBLIC" as const,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "demo_offer_2",
      organization_id: "org_demo_preview",
      store_id: "demo_store_preview",
      offer_type: "PRODUCT" as const,
      inventory_tracking: false,
      name: "Gói Trải Nghiệm Thiết Bị Đeo Sức Khỏe HealthTrack",
      slug: "trai-nghiem-healthtrack",
      price: 4900000,
      compare_at_price: 5500000,
      short_description: "Tặng kèm 2 dây đeo thể thao cao cấp và gói đo thể lực 1 năm miễn phí.",
      image_url: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
      status: "ACTIVE" as const,
      visibility: "PUBLIC" as const,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
};
